/**
 * «Copyright 2025 Roberto Reinosa Fernández»
 * 
 * This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * */

package com.RRF.ThresholdXpert;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author roberto
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    public static String entrada;
    
    public Interfaz() {
        
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/com/RRF/ThresholdXpert/logo/Logo ThresholdXpert.png")).getImage());
        
        setLocationRelativeTo(null);      
   
        setTitle("ThresholdXpert 1.0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogEntrada = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        DialogSalida = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        DialogSalida1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        DialogSalida2 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        DialogSalida3 = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        DialogSalida4 = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        DialogSalida5 = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        DialogSalida6 = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        DialogSalida7 = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        DialogEntrada.setMinimumSize(new java.awt.Dimension(1000, 500));

        jFileChooser1.setMaximumSize(new java.awt.Dimension(1000, 500));
        jFileChooser1.setMinimumSize(new java.awt.Dimension(1000, 500));
        jFileChooser1.setPreferredSize(new java.awt.Dimension(1000, 500));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        DialogEntrada.getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        DialogSalida.setSize(new java.awt.Dimension(950, 400));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout DialogSalidaLayout = new javax.swing.GroupLayout(DialogSalida.getContentPane());
        DialogSalida.getContentPane().setLayout(DialogSalidaLayout);
        DialogSalidaLayout.setHorizontalGroup(
            DialogSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        DialogSalidaLayout.setVerticalGroup(
            DialogSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        DialogSalida1.setSize(new java.awt.Dimension(950, 400));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout DialogSalida1Layout = new javax.swing.GroupLayout(DialogSalida1.getContentPane());
        DialogSalida1.getContentPane().setLayout(DialogSalida1Layout);
        DialogSalida1Layout.setHorizontalGroup(
            DialogSalida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        DialogSalida1Layout.setVerticalGroup(
            DialogSalida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        DialogSalida2.setSize(new java.awt.Dimension(950, 400));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout DialogSalida2Layout = new javax.swing.GroupLayout(DialogSalida2.getContentPane());
        DialogSalida2.getContentPane().setLayout(DialogSalida2Layout);
        DialogSalida2Layout.setHorizontalGroup(
            DialogSalida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        DialogSalida2Layout.setVerticalGroup(
            DialogSalida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        DialogSalida3.setSize(new java.awt.Dimension(950, 400));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout DialogSalida3Layout = new javax.swing.GroupLayout(DialogSalida3.getContentPane());
        DialogSalida3.getContentPane().setLayout(DialogSalida3Layout);
        DialogSalida3Layout.setHorizontalGroup(
            DialogSalida3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        DialogSalida3Layout.setVerticalGroup(
            DialogSalida3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        DialogSalida4.setSize(new java.awt.Dimension(950, 400));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout DialogSalida4Layout = new javax.swing.GroupLayout(DialogSalida4.getContentPane());
        DialogSalida4.getContentPane().setLayout(DialogSalida4Layout);
        DialogSalida4Layout.setHorizontalGroup(
            DialogSalida4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        DialogSalida4Layout.setVerticalGroup(
            DialogSalida4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        DialogSalida5.setSize(new java.awt.Dimension(950, 400));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout DialogSalida5Layout = new javax.swing.GroupLayout(DialogSalida5.getContentPane());
        DialogSalida5.getContentPane().setLayout(DialogSalida5Layout);
        DialogSalida5Layout.setHorizontalGroup(
            DialogSalida5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        DialogSalida5Layout.setVerticalGroup(
            DialogSalida5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        DialogSalida6.setSize(new java.awt.Dimension(950, 400));

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane7.setViewportView(jTextArea7);

        javax.swing.GroupLayout DialogSalida6Layout = new javax.swing.GroupLayout(DialogSalida6.getContentPane());
        DialogSalida6.getContentPane().setLayout(DialogSalida6Layout);
        DialogSalida6Layout.setHorizontalGroup(
            DialogSalida6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        DialogSalida6Layout.setVerticalGroup(
            DialogSalida6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        DialogSalida7.setSize(new java.awt.Dimension(950, 400));

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane8.setViewportView(jTextArea8);

        javax.swing.GroupLayout DialogSalida7Layout = new javax.swing.GroupLayout(DialogSalida7.getContentPane());
        DialogSalida7.getContentPane().setLayout(DialogSalida7Layout);
        DialogSalida7Layout.setHorizontalGroup(
            DialogSalida7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        DialogSalida7Layout.setVerticalGroup(
            DialogSalida7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 520));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 520));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 123, 255));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Input");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 30, 120, 35);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Input file:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 71, 17);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(136, 136, 136));
        jLabel2.setText("No file selected");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 50, 190, 16);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Search values:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 166, 160, 17);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 186, 210, 24);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 310, 340, 24);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Thresholds:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 290, 160, 17);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 370, 340, 24);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Prediction values:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 350, 340, 17);

        jButton2.setBackground(new java.awt.Color(220, 53, 69));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(254, 254, 254));
        jButton2.setText("Cancel");
        jButton2.setMaximumSize(new java.awt.Dimension(67, 28));
        jButton2.setMinimumSize(new java.awt.Dimension(67, 28));
        jButton2.setPreferredSize(new java.awt.Dimension(67, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 430, 160, 35);

        jButton3.setBackground(new java.awt.Color(40, 167, 69));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(254, 254, 254));
        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 430, 160, 35);

        jComboBox1.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Calculate thresholds", "Individual prediction", "File prediction" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(30, 120, 340, 34);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Calculation type:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 90, 150, 17);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText(" Maximum values:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 227, 160, 17);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(30, 247, 210, 24);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Threads:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(290, 200, 90, 17);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(280, 230, 80, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DialogEntrada.setLocationRelativeTo(null);
        DialogEntrada.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        
        String command = evt.getActionCommand();
         
        if(command.equals(JFileChooser.APPROVE_SELECTION)){
                           
            String ruta = String.valueOf(jFileChooser1.getSelectedFile()) + "/";
           
            entrada = ruta;
                
            String rutaSalida = "... ";
            
            if(ruta.length() <= 25){
                
                rutaSalida = ruta;
                
            }else{
            
                for(int i = ruta.length()- 25; i < ruta.length(); i++){
                
                    rutaSalida += ruta.toCharArray()[i];
            
                }
            
            }
            
            jLabel2.setText(rutaSalida);
            
            DialogEntrada.dispose();
            
        }else if(command.equals(JFileChooser.CANCEL_SELECTION)){
            
            DialogEntrada.dispose();
            
        }
        
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        jButton3.setEnabled(false);
        
        DialogSalida.setVisible(false);       
        DialogSalida1.setVisible(false);        
        DialogSalida2.setVisible(false);        
        DialogSalida3.setVisible(false);        
        DialogSalida4.setVisible(false);        
        DialogSalida5.setVisible(false);        
        DialogSalida6.setVisible(false);        
        DialogSalida7.setVisible(false);
        
        switch (jComboBox1.getSelectedIndex()) {
            
            case 1:
                
                int totalHilos;
                
                if(jTextField5.getText().equals("")){
                    
                    jTextField5.setText("1");
                    
                }
                
                totalHilos = Integer.parseInt(jTextField5.getText());
                
                if(totalHilos > 8){
                    
                    jTextField5.setText("8");
                    totalHilos = 8;
                    
                }else if(totalHilos < 1){
                    
                    jTextField5.setText("1");
                    totalHilos = 1;
                    
                }
                                 
                if(totalHilos >= 1){
                                        
                    Hilo_Calcular_Puntos_Corte puntosCorte = new Hilo_Calcular_Puntos_Corte(entrada, jTextField1.getText(), jTextField4.getText());                      
                                      
                }
                
                if(totalHilos >= 2){
                                        
                    Hilo_Calcular_Puntos_Corte2 puntosCorte2 = new Hilo_Calcular_Puntos_Corte2(entrada, jTextField1.getText(), jTextField4.getText());                      
                                      
                }
                
                if(totalHilos >= 3){
                                        
                    Hilo_Calcular_Puntos_Corte3 puntosCorte3 = new Hilo_Calcular_Puntos_Corte3(entrada, jTextField1.getText(), jTextField4.getText());                      
                                      
                }
                
                if(totalHilos >= 4){
                                        
                    Hilo_Calcular_Puntos_Corte4 puntosCorte4 = new Hilo_Calcular_Puntos_Corte4(entrada, jTextField1.getText(), jTextField4.getText());                      
                                      
                }
                
                if(totalHilos >= 5){
                                        
                    Hilo_Calcular_Puntos_Corte5 puntosCorte5 = new Hilo_Calcular_Puntos_Corte5(entrada, jTextField1.getText(), jTextField4.getText());                      
                                      
                }
                
                if(totalHilos >= 6){
                                        
                    Hilo_Calcular_Puntos_Corte6 puntosCorte6 = new Hilo_Calcular_Puntos_Corte6(entrada, jTextField1.getText(), jTextField4.getText());                      
                                      
                }
                
                if(totalHilos >= 7){
                                        
                    Hilo_Calcular_Puntos_Corte7 puntosCorte7 = new Hilo_Calcular_Puntos_Corte7(entrada, jTextField1.getText(), jTextField4.getText());                      
                                      
                }
                
                if(totalHilos == 8){
                                        
                    Hilo_Calcular_Puntos_Corte8 puntosCorte8 = new Hilo_Calcular_Puntos_Corte8(entrada, jTextField1.getText(), jTextField4.getText());                      
                                      
                }
                       
                break;
                
            case 2:
                                    
                Hilo_Predictor_Puntos_Corte predictorPuntosCorteIndividual = new Hilo_Predictor_Puntos_Corte(1, "", jTextField3.getText(), jTextField2.getText());                 
                break;
                
            case 3:
   
                Hilo_Predictor_Puntos_Corte predictorPuntosCorteMultiple = new Hilo_Predictor_Puntos_Corte(2, entrada, "", jTextField2.getText());
                break;
                
            default:
                
                DialogSalida.setLocationRelativeTo(null);
                DialogSalida.setVisible(true);
                jTextArea1.setText("ERROR");
                jButton3.setEnabled(true);
                
                break;
                
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Cancelar_Hilos.cargarCancelarHilos();
        jButton3.setEnabled(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        switch (jComboBox1.getSelectedIndex()) {
           
            case 1:
                
                jButton1.setEnabled(true);
                jTextField1.setEnabled(true);
                jTextField4.setEnabled(true);
                jTextField2.setEnabled(false);
                jTextField3.setEnabled(false);
                jTextField5.setEnabled(true);
                break;
                
            case 2:
                
                jButton1.setEnabled(false);
                jTextField1.setEnabled(false);
                jTextField4.setEnabled(false);
                jTextField2.setEnabled(true);
                jTextField3.setEnabled(true);
                jTextField5.setEnabled(false);
                break;
                
            case 3:
                
                jButton1.setEnabled(true);
                jTextField1.setEnabled(false);
                jTextField4.setEnabled(false);
                jTextField2.setEnabled(true);
                jTextField3.setEnabled(false);
                jTextField5.setEnabled(false);
                break;
                
            default:
                
                jButton1.setEnabled(true);
                jTextField1.setEnabled(true);
                jTextField4.setEnabled(true);
                jTextField2.setEnabled(true);
                jTextField3.setEnabled(true);
                jTextField5.setEnabled(true);
                break;
                
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        
               
        UIManager.setLookAndFeel(new NimbusLookAndFeel());
        
        UIManager.put("TextField[Focused].borderPainter", new Color(255, 255, 255));
        UIManager.put("nimbusSelectionBackground", new Color(255, 255, 255));
                        
        UIManager.put("controlShadow", new Color(255, 255, 255));
        UIManager.put("control",new Color(255, 255, 255));
        UIManager.put("nimbusSelectionBackground", new Color(233, 84, 32));
        UIManager.put("nimbusFocus", new Color(230, 230, 230));
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogEntrada;
    public static javax.swing.JDialog DialogSalida;
    public static javax.swing.JDialog DialogSalida1;
    public static javax.swing.JDialog DialogSalida2;
    public static javax.swing.JDialog DialogSalida3;
    public static javax.swing.JDialog DialogSalida4;
    public static javax.swing.JDialog DialogSalida5;
    public static javax.swing.JDialog DialogSalida6;
    public static javax.swing.JDialog DialogSalida7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JScrollPane jScrollPane6;
    public static javax.swing.JScrollPane jScrollPane7;
    public static javax.swing.JScrollPane jScrollPane8;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    public static javax.swing.JTextArea jTextArea3;
    public static javax.swing.JTextArea jTextArea4;
    public static javax.swing.JTextArea jTextArea5;
    public static javax.swing.JTextArea jTextArea6;
    public static javax.swing.JTextArea jTextArea7;
    public static javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
